language: bash

sudo: required

services:
  - docker

before_script:
    - CURDIR=$PWD
    - ./edjangerinstall.sh --alias
    - git clone --branch=master https://github.com/sstephenson/bats.git /tmp/bats
    - cd /tmp/bats; ./install.sh /home/travis; rm -rf /tmp/bats
    - cd $CURDIR/tests

script:
    - bats --tap edjanger_tests.bats
