language: bash

before_script:
    - git clone --branch=master https://github.com/sstephenson/bats.git /tmp/bats
    - CURDIR=$PWD
    - cd /tmp/bats; ./install.sh /home/travis; rm -rf /tmp/bats
    - cd $CURDIR

script:
    - bats --tap tests/edockerinit_test.bats

