language: bash

before_script:
    - git clone --branch=master https://github.com/sstephenson/bats.git /home/travis/bats
    - PATH=$PATH:/home/travis/bats/bats-master/libexec:/home/travis/bats/bats-master/bin

script:
    - bats tests/edockerinit_test.bats

