language: bash

before_script:
    - curl -O "https://github.com/sstephenson/bats/archive/master.zip"
    - unzip master.zip
    - mv bats-master /home/travis/
    - PATH=$PATH:/home/travis/bats-master/libexec:/home/travis/bats-master/bin

script:
    - bats tests/edockerinit_test.bats

