language: bash

before_script:
    - git clone --branch=master https://github.com/sstephenson/bats.git /tmp/bats
    - cd /tmp/bats; ./install.sh /home/travis
    #- PATH=$PATH:/home/travis/bats/libexec:/home/travis/bats/bin

script:
    - bats pamtrak06/edocker/tests/edockerinit_test.bats

