site_name: edjanger
site_url: https://pamtrak06.github.io/edjanger
repo_url: https://github.com/pamtrak06/edjanger
repo_name: 'GitHub'
site_description: docker cli aliases configuration simplify
site_author: pamtrak06@gmail.com
copyright: MIT licence, pamtrak06@gmail.com
theme: material
#theme: cinder
#theme: readthedocs
#theme: bootstrap
#theme : cluster
#extra_css: [extra.css]
pages:
- Home: index.md
- 'How to': 'howto.md'
- 'Api doc': 'api/api.md'
- 'About': 'about.md'
extra:
  logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
#markdown_extensions:
#  - toc:
#    permalink: '#'
